apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  annotations:
    iam.gke.io/gcp-service-account: backend-sa@${PROJECT_ID}.iam.gserviceaccount.com

---
apiVersion: v1
kind: Secret
metadata:
  name: cloudsql-instance-credentials
type: Opaque
data:
  credentials.json: ${BASE64_ENCODED_CREDENTIALS}