apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  annotations:
    iam.gke.io/gcp-service-account: terraform-sa@dspl-24-poc.iam.gserviceaccount.com  # GCP service account to impersonate
